### PR TITLE
Wrapper pixi.js library

### PR DESCRIPTION
**Pull request by Maghwyn**

### CODE REVIEW

**Comment by Maghwyn** [comment]
CodeFactor issues :

- eventemitter3 - typing and context any.
Resolvable : I don't think so.

**Comment by Maghwyn** [comment]
> CodeFactor issues :
> 
>     * eventemitter3 - typing and context any.
>       Resolvable : I don't think so.

Fixed 13 of the 15 issues.
The last 2 can't be fixed tho, as the any type is necessary there.

**Comment by Maghwyn** [comment]
> > CodeFactor issues :
> > ```
> > * eventemitter3 - typing and context any.
> >   Resolvable : I don't think so.
> > ```
> 
> Fixed 13 of the 15 issues. The last 2 can't be fixed tho, as the any type is necessary there.

Converted the two 'any' to 'unknown'

**Review by Loule95450 — APPROVED** [review]
👍

**Comment by Maghwyn** [comment]
It's taking too much time to merge this PR when it's necessary. It's whatever i'll just do it.

**Pull request merged**
