### PR TITLE
[Feature] - Add QRCode

### PR DESCRIPTION
**Pull request by AyakorK**
This PR is made to create a QRCode that will depend on the courseId and the userId using a temporary token that will refresh every 3 minutes.

Just some warnings
-  Actually there is an URL used on Ngrok is obviously obsolete , we need to replace it with a environment variable or simply wait for the instance to be online to not have this necessity of hosting in a ngrok (I tried to make an env variable but didn't work)

### CODE REVIEW

**Review by Loule95450 — CHANGES_REQUESTED** [review]
Check CodeFactor Maintainability 
[Here](https://www.codefactor.io/repository/github/codingfactory-repos/coding-tools/pull/175)

**Review by Loule95450 — CHANGES_REQUESTED** [review]
[The warning Unexpected any. Specify a different type means that you are using the any type which is not recommended by TypeScript because it disables type checking and can lead to errors](https://stackoverflow.com/questions/58467000/how-to-bypass-warning-unexpected-any-specify-a-different-type-typescript-eslin)[1](https://stackoverflow.com/questions/58467000/how-to-bypass-warning-unexpected-any-specify-a-different-type-typescript-eslin)[2](https://stackoverflow.com/questions/58870856/warning-unexpected-any-specify-a-different-type-typescript-eslint-no-explicit)[3](https://stackoverflow.com/questions/69170917/eslint-unexpected-any-specify-a-different-type-typescript-eslint-no-explicit).

[In your case, you can replace any with unknown, which is a safer alternative that requires you to check the type before using it](https://stackoverflow.com/questions/58467000/how-to-bypass-warning-unexpected-any-specify-a-different-type-typescript-eslin)[1](https://stackoverflow.com/questions/58467000/how-to-bypass-warning-unexpected-any-specify-a-different-type-typescript-eslin). For example:

async generateTempToken$payload: Record<string, unknown>$ {
  // do something with payload
}
[Alternatively, you can specify a more precise type for your payload if you know what properties it has](https://stackoverflow.com/questions/58870856/warning-unexpected-any-specify-a-different-type-typescript-eslint-no-explicit)[2](https://stackoverflow.com/questions/58870856/warning-unexpected-any-specify-a-different-type-typescript-eslint-no-explicit). For example:

interface Payload {
  name: string;
  age: number;
}

async generateTempToken$payload: Payload$ {
  // do something with payload
}
I hope this helps.

**Review by Loule95450 — APPROVED** [review]
👍

**Review by RuKaSuu — APPROVED** [review]
LGTM

**Comment by Loule95450** [comment]
Delete ?

**Pull request merged**
